---
- name: Check if template exists
  ovirt_template_info:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ template_name }} and datacenter={{ template_cluster }}"
  register: template_info

- name: Create oVirt image template
  include_role:
    name: ovirt.image-template
  when: template_info.ovirt_templates | length == 0
