---
 - name: Wait for VMs IPv4
   ovirt_vm_facts:
     auth: "{{ ovirt_auth }}"
     pattern: "name={{ vm_name_from_list }}"
     fetch_nested: true
     nested_attributes: ips
   until: "ovirt_vms | ovirtvmipv4 | length > 0"
   retries: 30
   delay: 10

 - name: Set Ip of the VM
   set_fact:
     vm_ips: "{{vm_ips + [ovirt_vms | ovirtvmipv4]}}"

 - name: Debugging
   debug:
     msg: "Ip of vm {{ovirt_vms | ovirtvmipv4}}"