---
- name: Parse sysbench output to  csv
  run_once: true
  shell: |
    cat "{{sysbench_output_file}}" | egrep " cat|threads:|transactions|tps|read/write|min:|avg:|max:" | tr -d "\n" | sed 's/Number of threads: /\n/g' | sed 's/\[/\n/g' | sed 's/[A-Za-z\/]\{1,\}://g'| sed 's/ \.//g' | sed -e 's/read\/write//g'  -e 's/per sec.)//g' -e 's/ms//g' -e 's/(//g' -e 's/^.*cat //g' | sed 's/ \{1,\}/,/g' > "{{sysbench_output_file}}".csv
  tags:
    - to_csv