---
- name: Gather from vm to profiling host
  run_once: true
  shell: "scp -r \"root@{{vm_ip}}\":\"{{results_root_folder}}\"/sysbench-results \"{{results_root_folder}}\"/vm_results/"
  tags:
    - gather_from_vm
    - gather_all_results

- name: Tar hypervisor stats
  archive:
    path: "{{results_root_folder}}/sysbench-results/hypervisor_stats-{{inventory_hostname}}"
    dest: "{{results_root_folder}}/sysbench-results/hypervisor_stats-{{inventory_hostname}}.tgz"
  tags:
    - tar_hypervisor_stats
    - never


- name: Gather hosts stats from other hosts
  shell: " scp -r {{results_root_folder}}/sysbench-results/hypervisor_stats-{{inventory_hostname}} root@{{groups['profiling_server'][0]}}:{{results_root_folder}}/sysbench-results/"
  when: "'profiling_server' not in group_names"
  tags:
    - gather_from_hosts
    - gather_all_results

- name: Gather from hosts to local
  delegate_to: 127.0.0.1
  run_once: true
  become: false
  shell: "scp -r root@{{groups['profiling_server'][0]}}:{{results_root_folder}} ./results{{results_suffix}} "
  tags:
    - gather_from_prof_serv_to_local
